# Generated by Django 5.0.4 on 2025-07-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyrun',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
