# Generated by Django 5.0.4 on 2025-07-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0002_strategyrun_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='strategy_name',
            field=models.CharField(default='My Strategy', max_length=100, unique=True),
        ),
    ]
